version: 2
jobs:
   build:
     docker:
       - image: docker:17.05.0-ce-git
     steps:
       - checkout
       - setup_remote_docker
       - run: docker info
       - run:
           name: Install dependencies
           command: |
              RUN apk --no-cache add curl \
              RUN apk add --no-cache bash \
              curl -fsSL get.docksal.io | sh
