version: 2
jobs:
   build:
     working_directory: /app
     docker:
       - image: jpetazzo/dind
     steps:
       - checkout
       - setup_remote_docker
       - run: docker info
       - run:
           name: Install dependencies
           command: |
              wget https://raw.githubusercontent.com/docksal/docksal/v1.4.0/bin/fin && mv fin /usr/local/bin/fin && chmod +x /usr/local/bin/fin
              fin update -y
              fin sysinfo
