version: 2
jobs:
   build:
     working_directory: /app
     docker:
       - image: jpetazzo/dind
     steps:
       - checkout
       - setup_remote_docker
       - run: docker info
       - run:
           name: Install dependencies
           command: |
              adduser --disabled-password --gecos '' ci && adduser ci sudo && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
              su ci
              cd /home/ci
              wget https://raw.githubusercontent.com/docksal/docksal/v1.4.0/bin/fin && sudo mv fin /usr/local/bin/fin && sudo chmod +x /usr/local/bin/fin
              curl -L https://github.com/docker/compose/releases/download/1.14.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
              fin update -y
              fin sysinfo
              git clone https://github.com/docksal/drupal8.git && cd drupal8
              fin init
