version: 2
jobs:
   build:
     docker:
       - image: gitlab/dind:latest
     steps:
       - checkout
       - setup_remote_docker
       - run: docker info
       - run:
           name: Install dependencies
           command: |
              curl -fsSL get.docksal.io | sh
