version: 2
jobs:
   build:
     working_directory: /app
     docker:
       - image: jpetazzo/dind
     steps:
       - checkout
       - setup_remote_docker
       - run: docker info
       - run: adduser --disabled-password --gecos '' ci && adduser ci sudo && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && su ci
       - run: cd /home/ci
       - run: wget https://raw.githubusercontent.com/docksal/docksal/v1.4.0/bin/fin && sudo mv fin /usr/local/bin/fin && sudo chmod +x /usr/local/bin/fin
       - run: curl -L https://github.com/docker/compose/releases/download/1.14.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
       - run: fin update -y
       - run: fin sysinfo
       - run: git clone https://github.com/docksal/drupal8.git && cd drupal8
       - run: fin init
