version: 2
jobs:
   build:
     working_directory: /app
     docker:
       - image: docker:17.05.0-ce-git
     steps:
       - checkout
       - setup_remote_docker
       - run: docker info
       - run:
           name: Install dependencies
           command: |
              docker build -t docksal-test-framework .
              echo "hi"
              docker run --name=kalabox-$CI_JOB_ID --privileged docksal-test-framework /home/ci/setup_docksal.sh
