version: 2
jobs:
   build:
     docker:
       - image: docker:17.05.0-ce-git
     steps:
       - checkout
       - setup_remote_docker
       - run: docker info
       - run:
           name: Install dependencies
           command: |
              apk --no-cache add curl \
              && curl -fsSL get.docksal.io | sh
